pool/pool/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from tastypie.api import Api
from django.views.generic import TemplateView
from apis.profile_response import *

v1_api = Api(api_name='v1')
v1_api.register(PrivateUserResource())
v1_api.register(PrivateProfileResource())
v1_api.register(PrivateCourseResource())
v1_api.register(PublicUserResource())
v1_api.register(PublicProfileResource())
v1_api.register(PublicCourseResource())


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(v1_api.urls)),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
]

pool/profiles/urls.py
from django.conf.urls import patterns, url
from profiles import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = patterns("",
    url(r'^$', TemplateView.as_view(template_name='create_profile.html'), name='index'),
    url(r'^edit/$', login_required(TemplateView.as_view(template_name='edit_profile.html')), name='edit'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
)

pool/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

class CourseType(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.name

class Profile(models.Model):
    user = models.ForeignKey(User)
    country = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=10)
    user_desciption = models.TextField()

    def __unicode__(self):
        return self.user.username

class Course(models.Model):
    course_name = models.CharField(max_length=100)
    course_type = models.ForeignKey(CourseType)
    course_desciption = models.TextField()
    owner = models.ForeignKey(Profile)

    def __unicode__(self):
        return self.course_name

# Create your models here.

pool/profiles/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, logout, login
from django.http import HttpResponseRedirect

def login_user(request):
    logout(request)
    if request.POST:
        password = request.POST['password']
        username = request.POST['username']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')
# Create your views here.

pool/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/underscore-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/backbone-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/backbone-tastypie.js' %}"></script>
</head>
<body>
    {% if request.user.is_active %} 
        <div> in {{request.user.username}} </div>
        <div> id {{request.user.id}} </div>
        <a href="{% url 'profile:logout' %}">Logout</a>
    {% else %}
        <form action="{% url 'profile:login' %}" method="POST">
            {% csrf_token %}
            <label>username: </label>
            <input name="username" type="text" id="username" value="">
            <label>password: </label>
            <input name="password" type="password" id="password" value="">
            <input type="submit" value="Go">
        </form>
    {% endif %}
    {% block content %}{% endblock %}
</body>
</html>

pool/templates/create_profile.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<script type="text/javascript">
$(function(){


    ProfileModel = Backbone.Model.extend({
        urlRoot: '/api/v1/profile/',
        defaults: {
            'username' : '',
            'password' : '',
            'email' : '',
            'country' : '',
            'city' : '',
            'zip_code' : '',
            'user_desciption' : ''
        }
    });

    ProfileView = Backbone.View.extend({
        el: '#profileForm',
        events: {
            'click #create': 'submitCreate'
        },
        initialize: function() {
            _.bindAll(this, 'submitCreate');
            this.model = new ProfileModel();
        },
        submitCreate: function() {
            var form = this.$el;
            var self = this;
            var unindexed_array = form.serializeArray();
            var data = {};

            unindexed_array.forEach(function(n){
                data[n.name] = n.value;
            });             
            self.model.set(data);
            self.model.save();
        },
    });

    return new ProfileView()
})
</script>
<h5>Vaaavaaa</h5>
<form id="profileForm">
    {% csrf_token %}
    <label>username: </label>
    <input name="username" type="text" id="username" value=""><br/>
    <label>password: </label>
    <input name="password" type="password" id="password" value=""><br/>
    <label>email: </label>
    <input name="email" type="text" id="email" value=""><br/>
    <label>country: </label>
    <input name="country" type="text" id="country" value=""><br/>
    <label>city: </label>
    <input name="city" type="text" id="city" value=""><br/>
    <label>zip code: </label>
    <input name="zip_code" type="text" id="zip_code" value=""><br/>
    <label>about your self: </label>
    <input name="user_desciption" type="text" id="user_desciption" value=""><br/>
    <input type="submit" id="create" value="Go">
</form>
{% endblock %}

pool/templates/edit_profile.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<script type="text/template" id="templateForm">
    <form id="profileForm">
        {% csrf_token %}
        <label>country: </label>
        <input name="country" type="text" id="country" value="<%= country %>"><br/>
        <label>city: </label>
        <input name="city" type="text" id="city" value="<%= city %>"><br/>
        <label>zip code: </label>
        <input name="zip_code" type="text" id="zip_code" value="<%= zip_code %>"><br/>
        <label>about your self: </label>
        <input name="user_desciption" type="text" id="user_desciption" value="<%= user_desciption %>"><br/>
        <input type="submit" id="change" value="Change">
    </form>
</script>
<script type="text/javascript">
$(function(){
    
    ProfileModel = Backbone.Model.extend({
        urlRoot: '/api/v1/private-profile/',
        defaults: {
            'country' : '',
            'city' : '',
            'zip_code' : '',
            'user_desciption' : ''
        }
    });

    ProfileView = Backbone.View.extend({
        el: '#profileForm',
        events: {
            'click #change': 'submitUpdate'
        },
        initialize: function() {
            _.bindAll(this, 'submitUpdate', 'render');
            this.model = new ProfileModel();
            var that = this;
            this.model.fetch({
                success: function(profile){
                    that.render(profile.toJSON());
                }
            })
        },
        submitUpdate: function() {
            var form = this.$el;
            var self = this;
            var unindexed_array = form.serializeArray();
            var data = {};

            unindexed_array.forEach(function(n){
                data[n.name] = n.value;
            });             
            self.model.set( data );
            self.model.save();
        },
        render: function(n) {
            var template = _.template( $("#templateForm").html(), n );
            this.$el.html( template );
        },
    });

    return new ProfileView()
})
</script>
<h5>Vaaavaaa</h5>
<div id="profileForm"></div>

{% endblock %}

pool/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<script type="text/javascript">
$(function(){
    RegistryUserModel = Backbone.Model.extend({
        
        initialize: function() {
        },

        urlRoot: function() {
            return '/api/v1/private_profile/'; //?format=json&private-user__id={{request.user.id}}';
        },

    });

    ProfileModel = Backbone.Model.extend({
        
        initialize: function() {
        },

        urlRoot: function() {
            return '/api/v1/profile';
        },

    });

    Profiles = Backbone.Collection.extend({
        
        model: ProfileModel,

        url : '/api/v1/profile/',
    });

    var profile = new RegistryUserModel();

    profile.fetch({
        success: function(profile) {
            var u = profile.toJSON();
            alert(JSON.stringify(u));
        }
    });
    // alert(profile.toJSON());

    // CollectionProfiles = new Profiles;



    ProfileView = Backbone.View.extend({
        
        el: '#booka',
        tagName: 'div',

        initialize: function() {
            _.bindAll(this, 'render');
            this.collection = new Profiles();
            var that = this;
            this.collection.fetch({
                success: function(profile) {
                    that.render(profile.toJSON());
                }
            });
        },

        template: _.template("<div> country: <%= country %>, ionfo: <%= user_desciption %>, city: <%= city  %> </div>"),

        render: function(profiles) {
            // alert(JSON.stringify(n));
            var that = this;
            profiles.forEach(function(profile){
                that.$el.append(that.template(profile))
            });
            // this.$el.html(this.template(n));
        }

    });

    return new ProfileView()

    // ExampleList = Backbone.View.extend({
        
    //     el: '#booka',

    //     initialize: function(options) {
    //         this.listenTo(CollectionProfiles, 'reset', this.addAll, this);
    //     },

    //     addOne: function(model) {
    //         var view = new ListItem ({ model : model });
    //         console.log(view.render().el);
    //         this.$el.append(view.render().el);
    //     },

    //     addAll: function() {
    //         var sample = this;
    //         Profiles.each(function(model){
    //             sample.addOne(model);
    //         });
    //     },

    //     render : function() {
    //         this.$el.html(this.template());
    //         return this;
    //     } 
    // });

    // CollectionProfiles.fetch({ reset : true })
})
</script>
<h5>BooBaa</h5>
<div id="booka"></div>

{% endblock %}